const types = {
  ADD_DOCUMENT: 'ADD_DOCUMENT',
  ADDING_DOCUMENT: 'ADDING_DOCUMENT',
  LIST_DOCUMENT: 'LIST_DOCUMENT',
  LIST_USER_DOCUMENT: 'LIST_USER_DOCUMENT',
  VIEW_DOCUMENT: 'VIEW_DOCUMENT',
  UPDATE_DOCUMENT: 'UPDATE_DOCUMENT',
  DELETE_DOCUMENT: 'DELETE_DOCUMENT',
  LOGIN_USER: 'LOGIN_USER',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_ACTIVE_USER: 'SET_ACTIVE_USER',
  CLEAR_ERROR: 'CLEAR_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SIGNUP_USER: 'SIGNUP_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  LIST_USERS: 'LIST_USERS',
  VIEW_USER: 'VIEW_USER',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_ERROR: 'UPDATE_ERROR',
  DELETE_USER: 'DELETE_USER',
  SEARCH_USER: 'SEARCH_USER',
  SEARCH_DOCUMENT: 'SEARCH_DOCUMENT',
  ADD_FLASH_MESSAGE: 'ADD_FLASH_MESSAGE',
  DELETE_FLASH_MESSAGE: 'DELETE_FLASH_MESSAGE'
};


export default types;
